language: python
python:
  - "3.6"
install:
  - pip install cython
  - python setup.py install

# functionality is tested in the pyranges package
script: cd ~/; python -c 'import ncls; print(ncls.__version__)'
